backend:
  name: github
  repo: Maks310/kukish-shop   # замініть на ваш GitHub
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Товари"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Ціна", name: "price", widget: "string" }
      - { label: "Опис", name: "body", widget: "markdown" }
      - { label: "Фото", name: "image", widget: "image" }
