backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Товари"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Ціна", name: "price", widget: "number" }
      - { label: "SKU", name: "sku", widget: "string", required: false }
      - { label: "Стан", name: "condition", widget: "string" }
      - { label: "Бренд", name: "brand", widget: "string", required: false }
      - { label: "Зображення", name: "image", widget: "image" }
      - { label: "Опис", name: "body", widget: "markdown" }
